apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - image: registry.gitlab.com/steniojr/podinfo:bef06b7e
        name: podinfo
        ports: 
        - containerPort: 9898
          protocol: TCP
        resources:
          requests:
            memory: "32Mi" 
            cpu: "128m"
          limits:
            memory: "64Mi"
            cpu: "256m"
        livenessProbe:
          httpGet:
            port: 9898
            path: /healthz
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 9898
            path: /healthz
          initialDelaySeconds: 5
          periodSeconds: 10
